language: ruby
rvm: 2.1.2
bundler_args: --without production
before_script:
  - psql -c 'create user heartbeat with superuser;' -U postgres
  - rake db:{create,migrate,seed}
addons:
  code_climate:
    repo_token: 39b99232832d5d9320eee2ba643cec77534a5aab44e7d760b65ccee7c41b7612
